server.port=8081
spring.application.name=menu-service
server.address=0.0.0.0

# Static resources
spring.web.resources.static-locations=classpath:/webapp/,classpath:/static/,classpath:/public/
spring.mvc.static-path-pattern=/**

# View settings
spring.mvc.view.prefix=/
spring.mvc.view.suffix=.html

# Logging
logging.level.com.example.demo=DEBUG


spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.drop-first=false

# JPA ???????
spring.jpa.hibernate.ddl-auto=validate
